spring:
  application:
    name: todo
  r2dbc:
    url: r2dbc:h2:mem://localhost/todo_list
    username: me
    password: 1234
  h2:
    console:
      enabled: true  # Enable H2 console for testing (optional)
  jackson:
    property-naming-strategy: SNAKE_CASE

  data:
    r2dbc:
      pool:
        initial-size: 10
        max-size: 20

  gateway:
      globalcors:
        routes:
        - id: todo 
          uri: http://localhost:8080  # URI of the service to route to
          predicates:
            - Path=/todo/**
        cors-configurations:
          '[/**]':  # Applies to all paths
            allowedOrigins: "*"
            allowedMethods: GET, POST, PUT, DELETE, OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
logging:
  level:
    org.springframework.web: DEBUG
